[package]
name = "passauf"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serialport = "4.7.0"
serde = { version = "1.0", features = ["derive"] }
bitflags = "2.8.0"
asn1 = "0.20.0"
